# Generated by Django 5.1.4 on 2024-12-18 19:51

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audiobooks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiobook',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='audiobook',
            name='book',
        ),
        migrations.AddField(
            model_name='audiobook',
            name='author',
            field=models.CharField(default='Unknown Author', max_length=100),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='description',
            field=models.TextField(default='No description available.'),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='narrator',
            field=models.CharField(default='Unknown Narrator', max_length=100),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='title',
            field=models.CharField(default='Untitled Audiobook', max_length=200),
        ),
        migrations.AddField(
            model_name='audiobook',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='audiobook',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
    ]
